name: Auto Comment on new issues
on:
  issues:
    type: [opened]

jobs:
   comment-with-action:
     runs-on: ubuntu-latest
     steps:
      - name: "Github Context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ (github.event.issue.number ) }}
          body: |
            This is a multi-line test comment
            it supporse to be automated by github actions. thanks
            
          reactions: '+1'
