name: Unit Testing

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python 3.10
      run: sudo apt install python3.10
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Update pip
      run: pip install --upgrade pip
      
    - name: Install unittest-xml-reporting
      run: pip install unittest-xml-reporting

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt file found."
        fi
      working-directory: ${{ github.workspace }}

    - name: Run Tests
      run: |
        python -m unittest discover -v
        if [ -d "test-reports" ] && [ -n "$(ls -A test-reports)" ]; then
          mv test-reports/*.xml .
        fi
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./*.xml
