name: Unit Testing

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install python 3.10
      run: sudo apt install python3.10
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: python-3.10
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest discover -v
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports
